config/routes.rb
Vanityapp::Application.routes.draw do
  resources :hotels do
    member do
      post :book
    end
  end

  match '/vanity(/:action(/:id(.:format)))', :controller => :vanity, :via => [:get, :post]
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :city, :name, :price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  use_vanity
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels/1/book
  def book
    @hotel = Hotel.find(params[:id])
    flash[:notice] = "Thank you for booking a room at #{@hotel.name}. Come again soon!"
    track! :bookings
    redirect_to hotels_path
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/vanity_controller.rb
class VanityController < ApplicationController
  include Vanity::Rails::Dashboard

  before_filter :authenticate if !Rails.env.development?

  protected

  def authenticate
    @auth ||= YAML.load(File.open(Rails.root + "config/auth.yml"))
    puts @auth.inspect
    authenticate_or_request_with_http_basic do |username, password|
      username == @auth["username"] && password == @auth["password"]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= form_for(@hotel) do |f| %>
  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% @hotel.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<h1>Listing hotels</h1>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hotels.each do |hotel| %>
  <tr>
    <td><%= hotel.name %></td>
    <td><%= hotel.city %></td>
    <td><%= hotel.price %></td>
    <td><%= link_to 'Show', hotel %></td>
    <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
    <td><%= link_to ab_test(:book_now), book_hotel_path(hotel), method: :post %></td>
    <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>

<%= render 'form' %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hotel.name %>
</p>

<p>
  <b>City:</b>
  <%= @hotel.city %>
</p>

<p>
  <b>Price:</b>
  <%= @hotel.price %>
</p>


<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vanityapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
  <p style="background-color: green; color: white; padding: 5px"><%= flash[:notice] %></p>
<% end %>

<%= yield %>

</body>
</html>